---
title:               Thomas Maxwell
tagline:             "Currently collaborating with Troop. When I'm not studying, coding or managing projects I'm playing tennis, reading and consuming copious amounts of music."
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Thomas Maxwell
twitter:             thmsmxwll
github:              thmsmxwll
email:               thmsmxwll@gmail.com
google_analytics_id: UA-17659949-3
disqus_shortname:    <%= ENV.fetch("disqus_shortname") { "thmsmxwll" } %>
soundcloud_id:       <%= ENV.fetch("soundcloud_id") { "6dc6eef4c9b5164adac378b48d18a9ca" } %>